<h1>linspace(), zeros(), ones(), and NumPy data types</h1>

In [10]:
import numpy as np


### linspace() function

In [3]:
np.linspace(5, 15, 9)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [4]:
np.linspace(5, 15, 9).size

9

In [6]:
np.linspace(5, 15, 10)

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

In [8]:
my_linspace = np.linspace(5, 15, 9, retstep=True)

In [9]:
my_linspace

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [11]:
my_linspace[1]

1.25

### zeros()

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### ones()


In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.ones((5,4)).size

20

In [18]:
len(np.ones((5,4)))

5

In [20]:
np.ones((5,4, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### Numpy and data types

In [22]:
np.zeros(4, dtype='int64')

array([0, 0, 0, 0], dtype=int64)

In [23]:
np.zeros(4)

array([0., 0., 0., 0.])

In [24]:
np.zeros(4, dtype='uint64')

array([0, 0, 0, 0], dtype=uint64)